/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UidemoRouteImport } from './routes/uidemo'
import { Route as UiInspectorRouteImport } from './routes/ui-inspector'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecondRouteImport } from './routes/second'
import { Route as ScreenshotRouteImport } from './routes/screenshot'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as PilotfishSettingsRouteImport } from './routes/pilotfish-settings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MediasRouteImport } from './routes/medias'
import { Route as LifecycleRouteImport } from './routes/lifecycle'
import { Route as FordevRouteImport } from './routes/fordev'
import { Route as FileExplorerRouteImport } from './routes/file-explorer'
import { Route as DeviceInfoRouteImport } from './routes/device-info'
import { Route as CpuUsageRouteImport } from './routes/cpu-usage'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CallLogsRouteImport } from './routes/call-logs'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BatteriesRouteImport } from './routes/batteries'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as IndexRouteImport } from './routes/index'

const UidemoRoute = UidemoRouteImport.update({
  id: '/uidemo',
  path: '/uidemo',
  getParentRoute: () => rootRouteImport,
} as any)
const UiInspectorRoute = UiInspectorRouteImport.update({
  id: '/ui-inspector',
  path: '/ui-inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecondRoute = SecondRouteImport.update({
  id: '/second',
  path: '/second',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenshotRoute = ScreenshotRouteImport.update({
  id: '/screenshot',
  path: '/screenshot',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotfishSettingsRoute = PilotfishSettingsRouteImport.update({
  id: '/pilotfish-settings',
  path: '/pilotfish-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MediasRoute = MediasRouteImport.update({
  id: '/medias',
  path: '/medias',
  getParentRoute: () => rootRouteImport,
} as any)
const LifecycleRoute = LifecycleRouteImport.update({
  id: '/lifecycle',
  path: '/lifecycle',
  getParentRoute: () => rootRouteImport,
} as any)
const FordevRoute = FordevRouteImport.update({
  id: '/fordev',
  path: '/fordev',
  getParentRoute: () => rootRouteImport,
} as any)
const FileExplorerRoute = FileExplorerRouteImport.update({
  id: '/file-explorer',
  path: '/file-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceInfoRoute = DeviceInfoRouteImport.update({
  id: '/device-info',
  path: '/device-info',
  getParentRoute: () => rootRouteImport,
} as any)
const CpuUsageRoute = CpuUsageRouteImport.update({
  id: '/cpu-usage',
  path: '/cpu-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CallLogsRoute = CallLogsRouteImport.update({
  id: '/call-logs',
  path: '/call-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BatteriesRoute = BatteriesRouteImport.update({
  id: '/batteries',
  path: '/batteries',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/batteries': typeof BatteriesRoute
  '/calendar': typeof CalendarRoute
  '/call-logs': typeof CallLogsRoute
  '/contacts': typeof ContactsRoute
  '/cpu-usage': typeof CpuUsageRoute
  '/device-info': typeof DeviceInfoRoute
  '/file-explorer': typeof FileExplorerRoute
  '/fordev': typeof FordevRoute
  '/lifecycle': typeof LifecycleRoute
  '/medias': typeof MediasRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/pilotfish-settings': typeof PilotfishSettingsRoute
  '/properties': typeof PropertiesRoute
  '/screenshot': typeof ScreenshotRoute
  '/second': typeof SecondRoute
  '/settings': typeof SettingsRoute
  '/terminal': typeof TerminalRoute
  '/ui-inspector': typeof UiInspectorRoute
  '/uidemo': typeof UidemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/batteries': typeof BatteriesRoute
  '/calendar': typeof CalendarRoute
  '/call-logs': typeof CallLogsRoute
  '/contacts': typeof ContactsRoute
  '/cpu-usage': typeof CpuUsageRoute
  '/device-info': typeof DeviceInfoRoute
  '/file-explorer': typeof FileExplorerRoute
  '/fordev': typeof FordevRoute
  '/lifecycle': typeof LifecycleRoute
  '/medias': typeof MediasRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/pilotfish-settings': typeof PilotfishSettingsRoute
  '/properties': typeof PropertiesRoute
  '/screenshot': typeof ScreenshotRoute
  '/second': typeof SecondRoute
  '/settings': typeof SettingsRoute
  '/terminal': typeof TerminalRoute
  '/ui-inspector': typeof UiInspectorRoute
  '/uidemo': typeof UidemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/batteries': typeof BatteriesRoute
  '/calendar': typeof CalendarRoute
  '/call-logs': typeof CallLogsRoute
  '/contacts': typeof ContactsRoute
  '/cpu-usage': typeof CpuUsageRoute
  '/device-info': typeof DeviceInfoRoute
  '/file-explorer': typeof FileExplorerRoute
  '/fordev': typeof FordevRoute
  '/lifecycle': typeof LifecycleRoute
  '/medias': typeof MediasRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/pilotfish-settings': typeof PilotfishSettingsRoute
  '/properties': typeof PropertiesRoute
  '/screenshot': typeof ScreenshotRoute
  '/second': typeof SecondRoute
  '/settings': typeof SettingsRoute
  '/terminal': typeof TerminalRoute
  '/ui-inspector': typeof UiInspectorRoute
  '/uidemo': typeof UidemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/batteries'
    | '/calendar'
    | '/call-logs'
    | '/contacts'
    | '/cpu-usage'
    | '/device-info'
    | '/file-explorer'
    | '/fordev'
    | '/lifecycle'
    | '/medias'
    | '/messages'
    | '/notifications'
    | '/pilotfish-settings'
    | '/properties'
    | '/screenshot'
    | '/second'
    | '/settings'
    | '/terminal'
    | '/ui-inspector'
    | '/uidemo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/batteries'
    | '/calendar'
    | '/call-logs'
    | '/contacts'
    | '/cpu-usage'
    | '/device-info'
    | '/file-explorer'
    | '/fordev'
    | '/lifecycle'
    | '/medias'
    | '/messages'
    | '/notifications'
    | '/pilotfish-settings'
    | '/properties'
    | '/screenshot'
    | '/second'
    | '/settings'
    | '/terminal'
    | '/ui-inspector'
    | '/uidemo'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/batteries'
    | '/calendar'
    | '/call-logs'
    | '/contacts'
    | '/cpu-usage'
    | '/device-info'
    | '/file-explorer'
    | '/fordev'
    | '/lifecycle'
    | '/medias'
    | '/messages'
    | '/notifications'
    | '/pilotfish-settings'
    | '/properties'
    | '/screenshot'
    | '/second'
    | '/settings'
    | '/terminal'
    | '/ui-inspector'
    | '/uidemo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRoute: typeof AppsRoute
  BatteriesRoute: typeof BatteriesRoute
  CalendarRoute: typeof CalendarRoute
  CallLogsRoute: typeof CallLogsRoute
  ContactsRoute: typeof ContactsRoute
  CpuUsageRoute: typeof CpuUsageRoute
  DeviceInfoRoute: typeof DeviceInfoRoute
  FileExplorerRoute: typeof FileExplorerRoute
  FordevRoute: typeof FordevRoute
  LifecycleRoute: typeof LifecycleRoute
  MediasRoute: typeof MediasRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PilotfishSettingsRoute: typeof PilotfishSettingsRoute
  PropertiesRoute: typeof PropertiesRoute
  ScreenshotRoute: typeof ScreenshotRoute
  SecondRoute: typeof SecondRoute
  SettingsRoute: typeof SettingsRoute
  TerminalRoute: typeof TerminalRoute
  UiInspectorRoute: typeof UiInspectorRoute
  UidemoRoute: typeof UidemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uidemo': {
      id: '/uidemo'
      path: '/uidemo'
      fullPath: '/uidemo'
      preLoaderRoute: typeof UidemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-inspector': {
      id: '/ui-inspector'
      path: '/ui-inspector'
      fullPath: '/ui-inspector'
      preLoaderRoute: typeof UiInspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/second': {
      id: '/second'
      path: '/second'
      fullPath: '/second'
      preLoaderRoute: typeof SecondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screenshot': {
      id: '/screenshot'
      path: '/screenshot'
      fullPath: '/screenshot'
      preLoaderRoute: typeof ScreenshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilotfish-settings': {
      id: '/pilotfish-settings'
      path: '/pilotfish-settings'
      fullPath: '/pilotfish-settings'
      preLoaderRoute: typeof PilotfishSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medias': {
      id: '/medias'
      path: '/medias'
      fullPath: '/medias'
      preLoaderRoute: typeof MediasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifecycle': {
      id: '/lifecycle'
      path: '/lifecycle'
      fullPath: '/lifecycle'
      preLoaderRoute: typeof LifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fordev': {
      id: '/fordev'
      path: '/fordev'
      fullPath: '/fordev'
      preLoaderRoute: typeof FordevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-explorer': {
      id: '/file-explorer'
      path: '/file-explorer'
      fullPath: '/file-explorer'
      preLoaderRoute: typeof FileExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device-info': {
      id: '/device-info'
      path: '/device-info'
      fullPath: '/device-info'
      preLoaderRoute: typeof DeviceInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpu-usage': {
      id: '/cpu-usage'
      path: '/cpu-usage'
      fullPath: '/cpu-usage'
      preLoaderRoute: typeof CpuUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-logs': {
      id: '/call-logs'
      path: '/call-logs'
      fullPath: '/call-logs'
      preLoaderRoute: typeof CallLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batteries': {
      id: '/batteries'
      path: '/batteries'
      fullPath: '/batteries'
      preLoaderRoute: typeof BatteriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRoute: AppsRoute,
  BatteriesRoute: BatteriesRoute,
  CalendarRoute: CalendarRoute,
  CallLogsRoute: CallLogsRoute,
  ContactsRoute: ContactsRoute,
  CpuUsageRoute: CpuUsageRoute,
  DeviceInfoRoute: DeviceInfoRoute,
  FileExplorerRoute: FileExplorerRoute,
  FordevRoute: FordevRoute,
  LifecycleRoute: LifecycleRoute,
  MediasRoute: MediasRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PilotfishSettingsRoute: PilotfishSettingsRoute,
  PropertiesRoute: PropertiesRoute,
  ScreenshotRoute: ScreenshotRoute,
  SecondRoute: SecondRoute,
  SettingsRoute: SettingsRoute,
  TerminalRoute: TerminalRoute,
  UiInspectorRoute: UiInspectorRoute,
  UidemoRoute: UidemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
